import {
  Activity,
  ArrowLeft,
  AudioLines,
  Bell,
  Bookmark,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CircleUserRound,
  Compass,
  Contrast,
  CreditCard,
  Eye,
  EyeOff,
  FileText,
  Globe2,
  GraduationCap,
  History,
  Info,
  Keyboard,
  Lightbulb,
  LockKeyhole,
  LogIn,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  MoreHorizontal,
  Palette,
  Paperclip,
  Pause,
  Play,
  Rocket,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Sparkles,
  Square,
  Star,
  Sun,
  Trash2,
  UserPlus,
  UserRound,
  Volume2,
  Waves,
  X,
  type LucideIcon,
} from 'lucide-react-native';

const icons = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  audioLines: AudioLines,
  bell: Bell,
  bookmark: Bookmark,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  compass: Compass,
  contrast: Contrast,
  creditCard: CreditCard,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  globe: Globe2,
  graduationCap: GraduationCap,
  help: CircleHelp,
  history: History,
  info: Info,
  keyboard: Keyboard,
  lightbulb: Lightbulb,
  lock: LockKeyhole,
  logIn: LogIn,
  logOut: LogOut,
  menu: Menu,
  message: MessageCircle,
  messageSquare: MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  more: MoreHorizontal,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  play: Play,
  profile: CircleUserRound,
  rocket: Rocket,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: ShieldCheck,
  sparkle: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  trash: Trash2,
  user: UserRound,
  userPlus: UserPlus,
  volume: Volume2,
  waves: Waves,
  x: X,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof icons;

export function AppIcon({
  name,
  size = 24,
  color = '#4A4A5B',
  strokeWidth = 2,
}: {
  name: AppIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Icon = icons[name];
  return <Icon accessible={false} color={color} size={size} strokeWidth={strokeWidth} />;
}
